version: '3'
services:
  home-admin:
    build:
      context: ./home-admin
    container_name: home-admin
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: admin-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
    volumes:
      - ./home-admin/config:/opt/app/config
      - ./home-admin/src:/opt/app/src
      - ./home-admin/package.json:/opt/package.json
      - ./home-admin/yarn.lock:/opt/yarn.lock
      - ./home-admin/.env:/opt/app/.env
      - ./home-admin/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    depends_on:
      - admin-db
    networks:
      - dev
  admin-db:
    image: mariadb:latest
    container_name: admin-db
    restart: unless-stopped
    platform: linux/amd64
    env_file: .env
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      - admin-data:/var/lib/mysql
    networks:
      - dev
  home:
    container_name: home
    restart: unless-stopped
    build:
      context: ./home
    command: yarn dev
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3030
    volumes:
      - ./home:/app
      - ./home/public:/app/public
    ports:
      - '3030:3030'
    depends_on:
      - home-admin
    networks:
      - dev

networks:
  dev:
    driver: bridge
volumes:
  admin-data:
